### ISSUE TITLE
problem in admin

### ISSUE THREAD

**Issue by artofhuman** [django-cache-machine/django-cache-machine#31] opened 2012-09-12 16:05 UTC
Example code
import caching.base

class NewsItem(caching.base.CachingMixin, IblockItem):

    class Meta:
        verbose_name = u'Новость'
        verbose_name_plural = u'Новости'

    preview_text = models.TextField(verbose_name=u'Краткое описание')

    objects = caching.base.CachingManager()

in admin this list object cached
When if i add object and press save and continue edit and pres link in in pathway in list no new item

**Comment by tobiasmcnulty** [comment] 2015-07-03 18:35
Closing this as a duplicate of #6 and #90

**Closed by tobiasmcnulty** 2015-07-03 18:35 UTC
